#!/bin/sh

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";


if [ "$#" -eq 1 ]; then
    python3 $SCRIPT_DIR/mango.py $1
else
    python3 $SCRIPT_DIR/mango.py
fi

