#!/bin/sh

python3 /Users/ch0pin/Desktop/medusa/mango.py


# if [ "$#" -eq 2 ]; then
#     python3 /Users/ch0pin/Desktop/medusa/mango.py $1 $2
# else
#     python3 /Users/ch0pin/Desktop/medusa/mango.py
# fi
