#!/bin/sh

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";



if [ "$#" -eq 2 ]; then
    python3 $SCRIPT_DIR/medusa.py $1 $2
else
    python3 $SCRIPT_DIR/medusa.py
fi